spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/app
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: none
  flyway:
    enabled: false
    location: classpath:db/migration
    default-schema: app
    schemas: app
springdoc:
  swagger-ui:
    path: /swagger-ui.html