CREATE TABLE IF NOT EXISTS app.puzzles (
    id UUID PRIMARY KEY,
    puzzle JSONB NOT NULL,
    user_id UUID NOT NULL REFERENCES app.users(id) ON DELETE CASCADE,
    status INTEGER NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP
);